services:
  # Databases
  mysql:
    build:
      context: mysql/
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: bihw
      MYSQL_USER: dev
      MYSQL_PASSWORD: pass
    command: --secure-file-priv="/data"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 60s
      retries: 5
