services:
  # Databases
  mysql:
    build:
      context: mysql/
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: bihw
      MYSQL_USER: dev
      MYSQL_PASSWORD: pass
    command: --secure-file-priv="/data"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 60s
      retries: 5

  influxdb:
    image: influxdb:2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: pass12345678
      DOCKER_INFLUXDB_INIT_ORG: bihw
      DOCKER_INFLUXDB_INIT_BUCKET: bihwb
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: mysecretadmintoken
      INFLUXDB_DB: bihw
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: pass12345678
    ports:
      - 8086:8086
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  grafana:
    image: grafana/grafana:11.3.1
    container_name: grafana
    restart: always
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: pass
    configs:
      - source: grafana_datasources_config
        target: /etc/grafana/provisioning/datasources/datasource.yaml
      - source: grafana_dashboard_provisioner
        target: /etc/grafana/provisioning/dashboards/main.yaml
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - 3000:3000
    depends_on:
      influxdb:
        condition: service_healthy
      mysql:
        condition: service_healthy


  # https://localhost:8443/nifi/login
  nifi:
    build:
      context: nifi/
      dockerfile: Dockerfile
    environment:
      SINGLE_USER_CREDENTIALS_USERNAME: admin
      SINGLE_USER_CREDENTIALS_PASSWORD: pass123456789
    volumes:
      - ./nifi/raw_data:/raw_data:rw
      # - ./nifi/drivers:/opt/nifi/nifi-current/lib
    ports:
      - 8443:8443

configs:
  grafana_datasources_config:
    file: ./grafana/config/datasources.yaml
  grafana_dashboard_provisioner:
    file: ./grafana/config/dashboard_provisioner.yaml
