{
 "title": "Airports",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "airport_count",
    "label": "Airport count",
    "query": "10,50,100,250,500,1000,1500,2000,2500,5000,7700"
   }
  ]
 },
 "panels": [
  {
   "title": "Airport Traffic Map",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "bihw",
     "rawSql": "SELECT\n  a.latitude,\n  a.longitude,\n  a.name AS airport_name,\n  COUNT(r.id) AS flight_count\nFROM\n  bihw.airports a\n  LEFT JOIN bihw.routes r ON a.id = r.source_airport_id\nGROUP BY\n  a.latitude,\n  a.longitude,\n  a.name\nORDER BY\n  flight_count DESC\nLIMIT\n  ${airport_count}\n"
    }
   ]
  },
  {
   "title": "Airport count by country",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "bihw",
     "rawSql": "SELECT \n    a.country AS country,  -- Ország\n    COUNT(*) AS airport_count  -- Repülőterek száma\nFROM \n    bihw.airports a\nGROUP BY \n    a.country\nORDER BY \n    airport_count DESC\nLIMIT ${airport_count}\n"
    }
   ]
  },
  {
   "title": "Most popular planes (top 15)",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "dataset": "bihw",
     "rawSql": "SELECT \n    p.name AS aircraft_name,\n    r.equipment AS aircraft_type,\n    COUNT(*) AS usage_count\nFROM \n    bihw.routes r\nJOIN \n    bihw.planes p\nON \n    r.equipment = p.iata_code\nWHERE \n    r.equipment IS NOT NULL\nGROUP BY \n    p.name, r.equipment\nORDER BY \n    usage_count DESC\nLIMIT 15;"
    }
   ]
  },
  {
   "title": "Most popular airports (top 15)",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "dataset": "bihw",
     "rawSql": "SELECT \n    a.name AS airport_name,\n    r.source_airport AS airport_id,\n    COUNT(*) AS flight_count\nFROM \n    bihw.routes r\nJOIN \n    bihw.airports a\nON \n    r.source_airport_id = a.id\nGROUP BY \n    r.source_airport, a.name\nORDER BY \n    flight_count DESC\nLIMIT 15;"
    }
   ]
  },
  {
   "title": "Most popular route sources and destinations (top 15)",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "dataset": "bihw",
     "rawSql": "SELECT \n    sa.country AS \"Source country\",           -- Forrás ország\n    da.country AS \"Destination country\",      -- Cél ország\n    COUNT(*) AS \"Flight count\"                -- Járatok száma\nFROM \n    bihw.routes r\nJOIN \n    bihw.airports sa ON r.source_airport_id = sa.id  -- Forrás repülőtér összekapcsolása\nJOIN \n    bihw.airports da ON r.destination_airport_id = da.id  -- Cél repülőtér összekapcsolása\nGROUP BY \n    sa.country, da.country                  -- Csoportosítás forrás- és célország szerint\nORDER BY \n    3 DESC\nLIMIT 15;"
    }
   ]
  },
  {
   "title": "Distribution of plane brands",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bihw",
     "rawSql": "SELECT \n\tSUBSTRING_INDEX(p.name , ' ', 1) AS Brand,\n\tcount(*) AS \"Count\"\nFROM planes p \nGROUP BY Brand\nORDER by 2 DESC"
    }
   ]
  },
  {
   "title": "Distribution of airline statuses",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bihw",
     "rawSql": "SELECT\n\ta.active AS \"Status\",\n\tcount(*)\nFROM airlines a\nGROUP BY a.active"
    }
   ]
  }
 ]
}