{
 "title": "Weather",
 "time": { "from": "2024-11-25T14:26:08.112Z", "to": "2024-12-01T00:12:54.683Z" },
 "templating": {
  "list": [
   {
    "name": "city",
    "label": "City",
    "query": {
     "query": "from(bucket: \"bihwb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)  // Az időtartomány szűrése\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather\")  // Csak a \"weather\" mérés adatai\n  |> group(columns: [\"city\"])  // A \"city\" tag szerint csoportosít\n  |> distinct(column: \"city\")  // Az egyedi városnevek kigyűjtése\n  |> sort(columns: [\"city\"], desc: false)  // Az eredmény városnév szerint rendezve\n  |> yield(name: \"unique_cities\")  // Eredmény elnevezése\n"
    }
   }
  ]
 },
 "panels": [
  { "title": "$city Airport", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "city" },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"bihwb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather\")\n  |> filter(fn: (r) => r[\"city\"] == \"${city}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temp\" or r[\"_field\"] == \"feels_like\" or r[\"_field\"] == \"temp_min\" or r[\"_field\"] == \"temp_max\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")\n"
    }
   ]
  },
  {
   "title": "Current Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bihwb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather\")\n  |> filter(fn: (r) => r[\"city\"] == \"${city}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temp\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")\n"
    }
   ]
  },
  {
   "title": "Current Wind speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bihwb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather\")\n  |> filter(fn: (r) => r[\"city\"] == \"${city}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wind_speed\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")\n"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "query": "from(bucket: \"bihwb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pressure\")\n  |> filter(fn: (r) => r[\"city\"] == \"${city}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"bihwb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\n  |> filter(fn: (r) => r[\"city\"] == \"${city}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}